LogLevel: debug
DryRun: true
MetricCommand:
  Path: "/bin/echo"
  Args: ["50"]
APIAddr: 127.0.0.1:9000
CapacityTagKey: Capacity
WorkingFilters:
  "tag:Role": ["spotscaler-example"]
PossibleTermination: 1
InstanceTypes:
  - c4.large
  - m4.large
AvailabilityZones:
  - ap-northeast-1b
  - ap-northeast-1c
CapacityByType:
  c4.large: 8
  m4.large: 6.5
ScalingOutThreshold: 75.0
ScalingInThreshold: 25.0
MinimumCapacity: 1.0
KeyName: 'default'
SubnetByAZ:
  ap-northeast-1b: subnet-a
  ap-northeast-1c: subnet-b
SecurityGroupIDs:
  - sg-
RedisURL: redis://127.0.0.1:6379
RedisKeyPrefix: spotscaler/